version: 2
updates:
  - directory: /
    package-ecosystem: npm
    schedule:
      interval: weekly
      day: monday
  - directory: /website
    package-ecosystem: npm
    schedule:
      interval: weekly
      day: monday
  - directory: /
    package-ecosystem: docker
    schedule:
      interval: weekly
      day: monday
