extends: '@janejeon'

ignorePatterns:
  - 'website/'
  - config/schema/*.compiled.js

overrides:
  - files: src/**/*.js
    extends: react-app
    rules:
      no-console: 1
  - files: scripts/**
    rules:
      no-console: 0
