extends: '@janejeon'

ignorePatterns:
  - 'website/'

overrides:
  - files: src/**/*.js
    extends: react-app
    rules:
      no-console: 1
  - files: scripts/**/*.js
    rules:
      no-console: 0
