extends:
  - standard
  - prettier
  - prettier/standard
  - plugin:react/recommended

plugins:
  - prettier
  - standard
  - react

rules:
  no-console: error

overrides:
  - files: '*.test.js'
    env:
      jest: true
  - files: '**/__utils__/**'
    env:
      jest: true

settings:
  react:
    version: detect
