version: '3'

services:
  database:
    image: circleci/postgres:alpine-ram
    ports:
      - 5432:5432
    env_file:
      - .db.env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 3s
      retries: 5
  redis:
    image: circleci/redis:alpine
    ports:
      - 6379:6379
    env_file:
      - .redis.env
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 3s
      retries: 3
