version: '3'

services:
  blink-app:
    build:
      context: .
      target: deps
    environment:
      NODE_ENV: dev
  postgres:
    image: circleci/postgres:alpine-ram
    ports:
      - 5432:5432
    environment:
      # keep this in sync w/ DATABASE_URL in your environment file/variable
      POSTGRES_DB: blink
      POSTGRES_USER: knex
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    image: circleci/redis:alpine
    ports:
      - 6379:6379
