services:
  keycloak:
    image: jboss/keycloak:12.0.4 # currently v13 is broken
    volumes:
      - ./config/keycloak.json:/mnt/keycloak.json:ro
    environment:
      DB_VENDOR: H2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_IMPORT: /mnt/keycloak.json
      PROXY_ADDRESS_FORWARDING: 'true'
      # KEYCLOAK_FRONTEND_URL: https://
    networks:
      - public
    labels:
      - traefik.enable=true
      - traefik.http.routers.keycloak.tls=true
      - traefik.http.routers.keycloak.rule=Host(`keycloak.localhost`)
      - traefik.http.services.keycloak.loadbalancer.server.port=8080

networks:
  public:
    external: true
