version: '3'

services:
  app:
    build:
      context: .
      target: deps
    depends_on:
      - postgres
      - redis
      - keycloak
    volumes:
      - .:/home/node
      - /home/node/node_modules/
    networks:
      - public
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.tls=true
      - traefik.http.routers.backend.tls=true
      # Route /app -> :4000
      - traefik.http.routers.frontend.rule=(Host(`localhost`) && PathPrefix(`/app`))
      - traefik.http.routers.frontend.priority=2
      - traefik.http.routers.frontend.service=frontend
      - traefik.http.services.frontend.loadbalancer.server.port=4000
      # Route / -> :3000
      - traefik.http.routers.backend.rule=Host(`localhost`)
      - traefik.http.routers.backend.priority=1
      - traefik.http.routers.backend.service=backend
      - traefik.http.services.backend.loadbalancer.server.port=3000
  traefik:
    image: traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik:/etc/traefik:ro
    networks:
      - public
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.rule=Host(`traefik.localhost`)
      - traefik.http.services.api@internal.loadbalancer.server.port=8080
  postgres:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      # keep this in sync w/ DATABASE_URL in your environment file/variable
      POSTGRES_DB: blink
      POSTGRES_USER: knex
      POSTGRES_HOST_AUTH_METHOD: trust
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - internal
  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    networks:
      - internal
  keycloak:
    image: jboss/keycloak:13
    volumes:
      - ./config/keycloak.json:/mnt/keycloak.json:ro
    environment:
      DB_VENDOR: H2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_IMPORT: /mnt/keycloak.json
      PROXY_ADDRESS_FORWARDING: 'true'
      KEYCLOAK_FRONTEND_URL: https://keycloak.localhost/auth
    networks:
      - public
    labels:
      - traefik.enable=true
      - traefik.http.routers.keycloak.tls=true
      - traefik.http.routers.keycloak.rule=Host(`keycloak.localhost`)
      - traefik.http.services.keycloak.loadbalancer.server.port=8080

networks:
  public:
    external: true
  internal: {}
