$id: Link
type: object
properties:
  id:
    type:
      - integer
      - string
    readOnly: true
  creatorId:
    $ref: User#/properties/id
  hash:
    type:
      - string
      - 'null'
    minLength: 4
    maxLength: 25
    pattern: "\\w+"
  originalUrl:
    type: string
    readOnly: true
  shortenedUrl:
    type: string
    readOnly: true
  brandedUrl:
    type:
      - string
      - 'null'
    readOnly: true
  meta:
    type: object
    properties:
      author:
        type:
          - string
          - 'null'
      date:
        type:
          - string
          - 'null'
        format: date
      description:
        type:
          - string
          - 'null'
      lang:
        type:
          - string
          - 'null'
      logo:
        type:
          - string
          - 'null'
        format: uri
      publisher:
        type:
          - string
          - 'null'
      title:
        type:
          - string
          - 'null'
    additionalProperties: false
required:
  - originalUrl
additionalProperties: false
