version: 2.1

orbs:
  node: circleci/node@3
  slack: circleci/slack@3

aliases:
  - &runner
    executor:
      name: node/default
  - &size
    resource_class: small

jobs:
  lint:
    <<: *runner
    <<: *size
    steps:
      - checkout
      - &install
        node/install-packages:
          include-branch-in-cache-key: false
          override-ci-command: npm ci --prefer-offline --no-audit
      - run:
          name: Lint (Prettier)
          command: npm run lint:prettier
      - run:
          name: Lint (ESLint)
          command: npm run lint:eslint -- --format junit --output-file reports/eslint/results.xml
      - &retrieve-junit
        store_test_results:
          path: reports
  test-frontend:
    <<: *runner
    <<: *size
    steps:
      - checkout
      - *install
      - run:
          name: Test CRA
          command: npm run test:nowatch:frontend -- -- --ci --runInBand --reporters=jest-junit --reporters=default
          environment:
            JEST_JUNIT_OUTPUT_DIR: reports/jest-frontend
      - *retrieve-junit
      - slack/notify-on-failure
  test-backend:
    <<: *size
    docker:
      - image: cimg/node:lts
      - image: circleci/postgres:alpine-ram
        environment:
          POSTGRES_DB: lynx
          POSTGRES_USER: knex
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - *install
      - run:
          name: Build
          command: npm run pretest
      - run:
          name: Test Express
          command: npm run test:nowatch:backend -- --ci --runInBand --reporters=jest-junit --reporters=default
          environment:
            JEST_JUNIT_OUTPUT_DIR: reports/jest-backend
      - *retrieve-junit
      - slack/notify-on-failure

workflows:
  build-and-test:
    jobs:
      - lint
      - test-frontend:
          context: shared-vars
          requires:
            - lint
      - test-backend:
          context: shared-vars
          requires:
            - lint
