version: 2

jobs:
  lint:
    docker:
      - &node
        image: circleci/node:lts
    steps:
      - checkout
      - &restore-cache
        restore-cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn --frozen-lockfile
      - save-cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn lint

  test:
    docker:
      - *node
      - image: circleci/mongo
    steps:
      - checkout
      - *restore-cache
      - run: yarn test --ci --runInBand
      - store_test_results:
          path: reports/junit
      - run: yarn coverage

  docs:
    docker:
      - *node
    steps:
      - checkout
      - *restore-cache
      - run: yarn docs:build
      - run: yarn docs:deploy

workflows:
  version: 2
  pipeline:
    jobs:
      - lint
      - test:
          requires:
            - lint
      - docs:
          requires:
            - docs
          filters:
            branches:
              only:
                - master
