version: 2

jobs:
  build:
    docker:
      - image: circleci/node:lts
      - image: circleci/mongo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: yarn --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Test
          environment:
            JEST_JUNIT_OUTPUT_NAME: reports/junit/jest/results.xml
          command: yarn test --coverage --ci --runInBand --reporters=default --reporters=jest-junit

      - store_test_results:
          path: reports/junit

      - run:
          name: Upload Coverage
          command: yarn coverage
