version: 2.1

orbs:
  node: circleci/node@3
  slack: circleci/slack@3

aliases:
  - &runner
    executor:
      name: node/default
  - &install
    node/install-packages:
      include-branch-in-cache-key: false
      override-ci-command: npm ci --prefer-offline --no-audit

jobs:
  lint:
    <<: *runner
    steps:
      - checkout
      - *install
      - run:
          name: Lint (Prettier)
          command: npm run lint:prettier
      - run:
          name: Lint (ESLint)
          command: npm run lint:eslint -- --format junit --output-file reports/eslint/results.xml
      - store_test_results:
          path: reports
  test:
    parameters:
      test-suite:
        type: string
    <<: *runner
    steps:
      - checkout
      - *install
      - setup_remote_docker
      - run:
          # todo: do we need to stand up containers even for frontend?
          name: Stand up containers
          command: docker-compose up -d
      - run:
          name: Build
          command: npm run pretest
      - run:
          name: Test
          command: npm run test:nowatch:<< parameters.test-suite >> -- --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_NAME: results.xml
            JEST_JUNIT_OUTPUT_DIR: reports/jest-<< parameters.test-suite >>
      - store_test_results:
          path: reports
      - slack/notify-on-failure

workflows:
  build-and-test:
    jobs:
      - lint
      - test:
          context: shared-vars
          requires:
            - lint
          matrix:
            parameters:
              test-suite:
                - frontend
                - backend
