version: 2.1

orbs:
  node: circleci/node@4
  slack: circleci/slack@3
  jira: circleci/jira@1

aliases:
  - &runner
    executor:
      name: node/default
      tag: lts
  - &size
    resource_class: small

jobs:
  lint:
    <<: *runner
    <<: *size
    steps:
      - checkout
      - &install-pnpm
        run:
          name: Install pnpm
          command: curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm
      - &install-modules
        node/install-packages:
          include-branch-in-cache-key: false
          override-ci-command: pnpm i --prefer-offline --shamefully-hoist --frozen-lockfile
          cache-path: ~/.pnpm-store
      - run:
          name: Lint (Prettier)
          command: pnpm run lint:prettier
      - run:
          name: Lint (ESLint)
          command: pnpm run lint:eslint -- --format junit --output-file reports/eslint/results.xml
      - &retrieve-junit
        store_test_results:
          path: reports
  test-frontend:
    <<: *runner
    <<: *size
    steps:
      - checkout
      - *install-pnpm
      - *install-modules
      - run:
          name: Test CRA
          command: pnpm run pretest && pnpm run test:nowatch:frontend -- -- --ci --runInBand --reporters=jest-junit --reporters=default
          environment:
            JEST_JUNIT_OUTPUT_DIR: reports/jest-frontend
      - *retrieve-junit
      - slack/notify-on-failure
      - jira/notify
  test-backend:
    <<: *size
    docker:
      - image: cimg/node:lts
        environment:
          DATABASE_URL: postgres://knex@localhost/blink
          REDIS_URL: redis://localhost
      - image: circleci/postgres:alpine-ram
        environment:
          POSTGRES_DB: blink
          POSTGRES_USER: knex
          POSTGRES_HOST_AUTH_METHOD: trust
      - image: circleci/redis:alpine
    steps:
      - checkout
      - *install-pnpm
      - *install-modules
      - run:
          name: Test Express
          command: pnpm run pretest && pnpm run test:nowatch:backend -- --ci --runInBand --reporters=jest-junit --reporters=default
          environment:
            JEST_JUNIT_OUTPUT_DIR: reports/jest-backend
      - *retrieve-junit
      - slack/notify-on-failure
      - jira/notify

workflows:
  build-and-test:
    jobs:
      - lint
      - test-frontend: &test-config
          context: shared-vars
          requires:
            - lint
      - test-backend:
          <<: *test-config
