User:
  type: object
  properties:
    id:
      type: string
    role:
      type: string
      enum:
        - user
        - admin
        - owner
      default: user
    name:
      type: string
      maxLength: 100
    avatar:
      type: string
      format: uri
      maxLength: 100
    deleted:
      type: boolean
      default: false
  required:
    - id
  additionalProperties: false

Link:
  type: object
  properties:
    hash:
      type: string
      minLength: 4
      maxLength: 25
      pattern: ^\w+$
    originalURL:
      type: string
      maxLength: 100
    meta:
      type: object
      properties:
        author:
          type: string
          maxLength: 100
        date:
          type: string
          format: date
        description:
          type: string
          maxLength: 100
        lang:
          type: string
          maxLength: 10
        logo:
          type: string
          format: uri
          maxLength: 100
        publisher:
          type: string
          maxLength: 100
        title:
          type: string
          maxLength: 100
      additionalProperties: false
  required:
    - originalURL
  additionalProperties: false
