User:
  type: object
  properties:
    id:
      type: string
    role:
      type: string
      enum:
        - user
        - admin
        - owner
      default: user
    name:
      type: string
    avatar:
      type: string
  required:
    - id
  additionalProperties: false

Link:
  type: object
  properties:
    id:
      type: integer
      readOnly: true
    hash:
      type: string
      minLength: 4
      maxLength: 20
    originalURL:
      type: string
      maxLength: 100
  required:
    - originalURL
  additionalProperties: false
