User:
  type: object
  properties:
    id:
      type: integer
      readOnly: true
    role:
      type: string
      enum:
        - user
        - admin
      default: user
    name:
      type: string
    avatar:
      type: string
      format: uri
    githubId:
      type: string
      writeOnly: true
    slackId:
      type: string
      writeOnly: true
  additionalProperties: false

Link:
  type: object
  properties:
    id:
      type: integer
      readOnly: true
    hash:
      type: string
      minLength: 4
      maxLength: 20
      pattern: ^\w+$
    originalURL:
      type: string
      maxLength: 100
  required:
    - originalURL
  additionalProperties: false
